config/routes.rb
Rails.application.routes.draw do
  get 'feedbacks', to: 'feedbacks#new'
  post 'feedbacks', to: 'feedbacks#create'
  get 'shoes', to: 'shoes#index'
  get 'shoes/:id', to: 'shoes#show'
  get 'about', to: 'pages#about'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
end

app/models/scraper.rb
class Scraper < ApplicationRecord
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  validates :brand, length: { minimum: 3 }, presence: true
  validates :model, length: { minimum: 3 }, presence: true
  validates :price, presence: true
  has_many :shoesizes
  include PgSearch::Model
  pg_search_scope :search_by_brand_and_model,
                  against: %i[brand model],
                  # using: { tsearch: { prefix: true } }
                  using: { trigram: {} }
end

app/models/shoesize.rb
class Shoesize < ApplicationRecord
  belongs_to :shoe
  validates :size, presence: true
  validates :stock, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  include Pagy::Backend
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def new
    @feedback = Feedback.new
  end

  def create
    @feedback = Feedback.new(feedback_params)
    if @feedback.valid?
      @feedback.save
      flash[:notice] = "Thank you for your message! We'll come back to you very soon 🙂"
      redirect_to shoes_path
    else
      render :new
    end
  end

  private

  def feedback_params
    params.require(:feedback).permit(:name, :email, :feedback)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:home]

  def home
    redirect_to :shoes
  end
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  def index
    if params[:search].present?
      # @shoes = Shoe.search_by_brand_and_model(params[:search].to_s)
      # @shoes = Shoe.find_by_sql("SELECT * from shoes WHERE
      #   upper(brand) like upper('%#{params[:search]}%')
      #   OR upper(model) like upper('%#{params[:search]}%')
      # ").order('price asc, brand asc, model asc')
      sql_query = "brand ILIKE :query OR model ILIKE :query"
      @pagy, @shoes = pagy(Shoe.where(sql_query, query: "%#{params[:search]}%")
        .order(price: :asc, brand: :asc, model: :asc))
    else
      @pagy, @shoes = pagy(Shoe.all.order(price: :asc, brand: :asc, model: :asc))
      # @shoes = Shoe.first(15).sort_by { |shoe| [shoe.price, shoe.brand, shoe.model] }
      # @shoes = Shoe.limit(25).order("RANDOM()").sort_by { |shoe| [shoe.price, shoe.brand, shoe.model] }
    end
  end

  def show
    @shoe = Shoe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/feedbacks/new.html.erb
<h1>Feedback</h1>
<p>Swingshoe is made for you! Please tell us what you want, expect, what you miss - and maybe what you like too?</p>
<%= simple_form_for @feedback do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :feedback, input_html: { rows: 7, style: 'width: 100%'} %>
  <%= f.button :submit, "Send", class: "btn button btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta property="og:url"                content="http://swingshoe.herokuapp.com/" />
    <meta property="og:title"              content="Swingshoe - Find your next favorite dance shoes" />
    <meta property="og:description"        content="Compare and search in one place swing dance shoes for lindy hop, balboa or collegiate shag" />
    <meta property="og:image"              content="/assets/swingshoe-og-picture-076c08814546212706312aadb194aaf79ce24c2f435bf861fb7062d06473750e.jpg" />
    <meta name="description"               content="Compare and search in one place swing dances shoes for lindy hop, balboa or collegiate shag"/>
    <title>SwingshoeBETA</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/banner' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <h1>About</h1>
  <div class="row content-2-col">
    <div class="col-md-6">
      <div class="text-2-col">
        <p>As a balboa lover, I need adequate shoes to dance. A vintage look, leather soles... I started crawling the web and Facebook groups... and found myself overwhelmed by the numerous options. There are now many shoemakers dedicated to swing dance! But to pick a pair of shoe, you need to visit each of their online shop. Or attend an event where they will be at. I wanted to see everyting in one place. This is how Swingshoe was born!</p>
        <p>If you want to know more or leave your impressions, please send me a message on the <%= link_to "Feedback form",  feedbacks_path, class: "inline-link" %> or <%= mail_to "hello.swingshoe@gmail.com", "by mail", class: "inline-link" %>.</p>
      </div>
    </div>
    <div class="col-md-6">
      <%= image_tag "swingshoe-og-picture.jpg", alt: "balboa shoes", class: "image-2-col" %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1520012538304-01a178a8d217?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80);">
  <div class="container">
    <h1>Swingshoe</h1>
    <p>Find your next pair of swing dance shoes</p>
    <!-- <a class="btn btn-flat" href="#">Apply now</a> -->
  </div>
</div>
<!-- <div>
  <%= render partial: 'shared/shoe', collection: @shoes  %>
</div> -->

<div>
  <%= yield :shoe %>
</div>

app/views/shared/_banner.erb
<nav class="banner navbar navbar-expand-md navbar-light">
  <%= link_to root_path, id: "logo", class: "navbar-brand" do %>
    Swingshoe<span class="beta">BETA</span>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><%= link_to "Shoes",     shoes_path,     class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "Feedback",  feedbacks_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "About",     about_path,     class: "nav-link" %></li>
    </ul>
  </div>
</nav>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar-lewagon.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://icon-library.net/images/baby-feet-icon/baby-feet-icon-3.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://icon-library.net/images/baby-feet-icon/baby-feet-icon-3.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shoes/index.html.erb
<div class="form-group sticky">
  <span></span>
  <form class="row">
    <input type="search" name="search" class="form-control searchinput col-md-9" placeholder="Search for a brand, model..." autofocus>
    <input type="submit" class="btn button btn-primary col-md-2 offset-md-1">
  </form>
</div>
<div class="row">
  <div class="announcement">
    The website includes 3 brands so far: <%= link_to "Slide and Swing", '/shoes?search=slide+and+swing', class: "inline-link" %>, <%= link_to "Saint-Savoy", '/shoes?search=saint+savoy', class: "inline-link" %> and <%= link_to "Swivells", '/shoes?search=swivells', class: "inline-link" %>. There are only female shoes and accessories. Please make your suggestions for our next brands and new features <%= link_to "here", feedbacks_path, class: "inline-link emphasis" %>!
  </div>
</div>
<div class='cards'>
  <% @shoes.each do |shoe|%>
  <div class="card">
    <%= link_to shoe.url, target: "_blank" do %>
    <%= image_tag shoe.image_url  %>
    <div class="card-infos">
      <div>
        <h2><%= shoe.model %></h2>
        <p><%= shoe.brand %></p>
      </div>
      <h2 class="card-info-pricing">€ <%= shoe.price %></h2>
    </div>
    <% end %>
  </div>
  <% end %>
</div>
<%== pagy_bootstrap_nav(@pagy) %>